services:
  - type: web
    name: streamer-scheduler-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npx serve -s build -l $PORT
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://stream-schedule-api.onrender.com
